post/: OSFC_2020_part2 added
3mdeb/news-and-ideas pull request #358
Opened 2020-12-10 15:36 UTC by KBanecka

2021-01-11 13:16 UTC, pietrushnic requested changes

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +installable, redistributable firmware, the approaches to it, and the next steps.
@miczyg1 can you comment on the real usefulness of this?
@KBanecka we should somehow add https://old.reddit.com/r/Amd/comments/kfqni7/osfc_2020_open_source_firmware_conference_pure/ggmqd8j/ and what is behind link pointed in my comment.

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> + The important status of the project that aims at porting linuxboot on HPE
```suggestion
The important status of the project that aims at porting LinuxBoot on HPE
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +proof of concept, and next steps. HPE seems to provide LinuxBoot-enabled
```suggestion
proof of concept, and next steps. What seems to be interesting HPE seems to provide LinuxBoot-enabled
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +measured launch.
```suggestion
measured launch. Interestingly there was a quite long discussion with [Eugene](https://www.platformsecuritysummit.com/2018/speaker/myers/) and [Jeremiah](linkedin.com/in/bluescreen/) about the importance of open-source implementation of D-RTM that works across the platforms. More to that we received information that open-sourcing [AMD SMM Supervisor](https://community.amd.com/t5/amd-business-blog/amd-and-microsoft-secured-core-pc/ba-p/418204#:~:text=AMD%20SMM%20Supervisor%20resides%20in,SMM%20code%20at%20run%20time) is planned.
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +* works with OpenTITAN chips (FPGA)
```suggestion
* works with OpenTITAN chips (FPGA)

Another great project, which we would happy to triage if only there would be enough resources in our pocket.
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +Controller and information about google plans in contributing to Zephyr OS.
```suggestion
Controller and information about google plans in contributing to Zephyr OS. This is definitely a big deal for us since we are engaged in Zephyr OS-based IoT firmware development for quite some time. You can check our blog posts about it [here](https://blog.3mdeb.com/tags/zephyr/). We looking for a commercial assignment that involves Zephyr-based EC.
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +arm ServerReady certificate applied to embedded systems
```suggestion
Arm ServerReady certificate applied to embedded systems
```

2021-01-11 13:16 UTC, pietrushnic commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +* there is no ISV ecosystem that Arm endorse for certification
@KBanecka this should be rewritten maybe by @TomaszAIR or @macpijan

2021-03-04 14:27 UTC, KBanecka commented on blog/content/post/2020-12-10-OSFC_2020_part2.md
> +* there is no ISV ecosystem that Arm endorse for certification
done by @TomaszAIR

2021-03-04 21:00 UTC, pietrushnic requested changes
@KBanecka one last fix before publication.

2021-04-14 16:25 UTC, merged