2021-12-14-secure-jtag-on-imx-soc.md
3mdeb/news-and-ideas pull request #458
Opened 2021-12-14 15:09 UTC by kotylamichal

: Fixes after Piotr review

2021-12-14 15:47 UTC, artur-rs approved these changes

2021-12-14 16:00 UTC, pietrushnic requested changes
Most of the problems were resolved. Thank you. There are some small remaining things.

Practice makes perfect.

2021-12-14 22:25 UTC, pietrushnic commented
@artur-rs @kotylamichal there are still minor correction to apply.

2021-12-15 07:20 UTC, kotylamichal commented on blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
> +with SJC (System JTAG controller) in a secure mode. Required patch work on
Added

2021-12-15 07:28 UTC, kotylamichal commented on blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
> +publicly available.
Fixed some misspells, I don't see more non-false errors (I use free version of Grammarly)

2021-12-15 07:29 UTC, kotylamichal commented on blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
> +```
Ok

2021-12-15 07:42 UTC, kotylamichal commented on blog/content/post/2021-12-14-secure-jtag-on-imx-soc.md
> +$ git clone -n git://git.code.sf.net/p/openocd/code openocd-code
@pietrushnic Our fork is to do before publishing this article, or it is an idea for the future?  If we found a way to deal with SJC from OpenOCD we can publish a new, our patch that allows working with more than i.MX6. This also can be an idea for a new article (tested other i.MX devices, new patch, our fork with applied patch)

2021-12-15 11:49 UTC, pietrushnic approved these changes

2021-12-15 14:57 UTC, merged